spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32774/test
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

